import { Scale, Shield, HeartHandshake, FileText, Search, Building2,
  Gavel, Users, Briefcase, Globe, BookOpen, AlertCircle, Flag, CreditCard } from 'lucide-react';

// --- Each subArea has name + detailed content ---
export interface SubArea { name: string; content: string; }

export const practiceData = [
  {
    slug: 'supreme-court',
    title: 'Supreme Court of India',
    category: 'Apex Court',
    tagline: 'The highest constitutional court — protecting fundamental rights of all citizens.',
    description: 'We assist in matters relating to Special Leave Petitions (SLP), constitutional disputes, appeals, writ petitions, review petitions, curative matters, legal drafting, case preparation, research support, briefing assistance, and strategic litigation coordination before the Supreme Court of India.',
    icon: Gavel,
    subAreas: [
      { name: 'SLP Drafting', content: 'A Special Leave Petition (SLP) under Article 136 is the primary route to the Supreme Court. We provide comprehensive SLP drafting — identifying grounds of challenge, structuring arguments, and preparing the entire petition with supporting documents, annexures, and urgent mention applications where needed.' },
      { name: 'Article 32 Writ Petitions', content: 'Article 32 gives every citizen the right to directly approach the Supreme Court for enforcement of fundamental rights. We draft writ petitions under Article 32 for matters involving violations of Articles 14, 19, 21, and other fundamental rights, along with interim relief applications and contempt petitions.' },
      { name: 'Constitutional Matters', content: 'Constitutional questions involving interpretation of the Constitution, challenge to legislation, separation of powers, and federal issues require specialized expertise. We provide research-based support for constitutional matters including involvement of the President, Governor, Parliament, and State Legislature.' },
      { name: 'Civil Appeals', content: 'Appeals from judgments of High Courts in civil matters can be brought before the Supreme Court. We assist in identifying appealable orders, drafting civil appeals, and providing complete litigation support including stay applications and interim measures during the pendency of appeals.' },
      { name: 'Criminal Appeals', content: 'Criminal appeals to the Supreme Court arise in serious criminal matters where High Court judgments require challenge. We assist in bail matters pending appeal, drafting criminal appeals, and coordinating with Supreme Court advocates for comprehensive representation.' },
      { name: 'Review Petitions', content: 'A Review Petition allows the Supreme Court to reconsider its own judgment when there is an error apparent on the face of the record or on discovery of new facts. We draft review petitions identifying specific legal errors and assist in the circulation process before the same bench.' },
      { name: 'Curative Petitions', content: 'A Curative Petition is the last judicial remedy before the Supreme Court after a Review Petition is dismissed. It must certify gross miscarriage of justice or violation of natural justice. We assist in exceptional cases meeting the strict criteria set out in Rupa Ashok Hurra v. Ashok Hurra.' },
      { name: 'Research & Briefing', content: 'Supreme Court litigation demands meticulous legal research. We provide comprehensive case research including precedent identification, constitutional analysis, comparative law insights, and concise case briefs. Our research covers Manupatra, SCC Online, and official Supreme Court records.' },
      { name: 'PIL Matters', content: 'Public Interest Litigation (PIL) under Article 32 allows any public-spirited citizen to approach the Supreme Court for matters of public importance. We assist in identifying PIL-worthy issues, drafting petitions, gathering evidence of public interest, and coordinating the litigation strategy.' },
      { name: 'Transfer Petitions', content: 'Transfer Petitions under Section 25 CPC or Section 406 CrPC allow parties to seek transfer of cases from one court to another — including transfer from a High Court to the Supreme Court or between states. We draft transfer petitions and represent parties before the Supreme Court.' },
      { name: 'Contempt of Court', content: 'Contempt of Court proceedings before the Supreme Court arise when its orders or the majesty of the court is disrespected. We assist in both initiating contempt proceedings against parties who violate Supreme Court orders, and defending against contempt notices.' },
    ],
    process: [
      { title: 'Case Eligibility', desc: 'Assessing whether the matter meets the threshold for Supreme Court — substantial question of law, constitutional importance, or gross injustice.' },
      { title: 'SLP / Appeal Drafting', desc: 'Comprehensive drafting of SLP, appeal, writ or review — including grounds, arguments, and all supporting documents.' },
      { title: 'Filing & Registry', desc: 'Filing in Supreme Court Registry with proper procedural compliance including urgent mention where needed.' },
      { title: 'Arguments & Representation', desc: 'Coordinating with Supreme Court advocates for hearings and final arguments before the Bench.' },
    ],
    related: ['High Courts', 'Constitutional Law', 'Civil Appeals', 'Criminal Appeals'],
    courts: ['Supreme Court of India, New Delhi'],
  },
  {
    slug: 'high-court',
    title: 'High Court Practice',
    category: 'High Courts',
    tagline: 'Expert litigation support across 8 major High Courts across India.',
    description: 'NyayaSutra provides legal assistance, drafting, litigation support, and strategic legal research for matters before various High Courts across India including Allahabad, Delhi, Karnataka, Calcutta, Madhya Pradesh, Madras, Chhattisgarh and Kerala High Courts.',
    icon: Building2,
    subAreas: [
      { name: 'Writ Petitions', content: 'Writ Petitions under Article 226 of the Constitution before High Courts are the primary remedy for enforcement of fundamental rights and other legal rights against the State and its instrumentalities. We draft writ petitions for certiorari, mandamus, prohibition, habeas corpus, and quo warranto — with complete supporting affidavits, documents, and interim applications.' },
      { name: 'Bail Matters', content: 'Bail applications before High Courts under Section 439 CrPC (now BNSS 2023) for regular bail, and Section 438 CrPC / 482 BNSS for anticipatory bail, require careful drafting and strong arguments on grounds of parity, antecedents, nature of offence, and personal liberty under Article 21. We draft comprehensive bail applications with supporting precedents and coordinate for urgent hearing.' },
      { name: 'Quashing Petitions', content: 'Under Section 482 CrPC / 528 BNSS, inherent powers of the High Court can be invoked to quash FIRs, charge sheets, and criminal proceedings that are an abuse of process of law, lack prima facie case, or are filed with malicious intent. We research, draft and argue quashing petitions with supporting case law from High Courts and the Supreme Court.' },
      { name: 'Civil Revisions', content: 'Civil Revision Petitions challenge orders of subordinate courts in civil matters where no appeal lies and the order is illegal, irregular, or based on wrong exercise of jurisdiction. We draft revision petitions identifying jurisdictional errors and incorrect application of law, along with stay applications.' },
      { name: 'Criminal Revisions', content: 'Criminal Revision Petitions challenge orders of Sessions Courts and Magistrates where the order is improper, illegal, or not in conformity with law. Common revision matters include sentence modifications, bail cancellations, and challenges to discharge orders. We provide comprehensive revision drafting and arguments.' },
      { name: 'Service Matters', content: 'Service law cases before High Courts involve matters of government employees — transfer, suspension, dismissal, promotion denial, seniority disputes, and departmental enquiries. We assist in writ petitions challenging arbitrary service actions and seek reinstatement, arrears, and other reliefs.' },
      { name: 'Constitutional Challenges', content: 'High Courts hear challenges to State legislation and executive actions under their plenary writ jurisdiction. We research constitutional validity arguments, draft petitions challenging laws violating fundamental rights or beyond legislative competence, and coordinate bench appearances.' },
      { name: 'Interim Relief Applications', content: 'Interim stay, injunction, or protection orders from the High Court are often critical to protect rights during pending litigation. We draft urgent interim applications with balance of convenience arguments, irreparable harm analysis, and prima facie case analysis — and coordinate for urgent listing.' },
      { name: 'Public Law Matters', content: 'PIL filings before High Courts for public interest issues — environmental protection, corruption, municipal failures, and administrative injustice — are a powerful tool for systemic change. We identify actionable public law issues, gather evidence, and draft High Court PILs with proper locus standi.' },
    ],
    process: [
      { title: 'Jurisdiction Analysis', desc: 'Identifying the correct High Court, bench, and division for the matter.' },
      { title: 'Petition Drafting', desc: 'Comprehensive drafting of writ, appeal, revision, or special application.' },
      { title: 'Filing & Service', desc: 'Complete filing with supporting documents, affidavits, and proper service.' },
      { title: 'Arguments', desc: 'Coordinating representation through hearings, interim relief, and final disposal.' },
    ],
    related: ['Supreme Court', 'District Courts', 'Constitutional Law', 'Criminal Law'],
    courts: ['Allahabad High Court', 'Delhi High Court', 'Karnataka High Court', 'Calcutta High Court', 'Madhya Pradesh High Court', 'Madras High Court', 'Chhattisgarh High Court', 'Kerala High Court'],
  },
  {
    slug: 'district-court',
    title: 'District Court Practice',
    category: 'Trial Courts',
    tagline: 'Foundation of day-to-day litigation — complete district court support.',
    description: 'District Courts are the primary courts of first instance in India. We provide legal support and litigation assistance in criminal matters, civil disputes, recovery suits, family disputes, property litigation, injunctions, consumer matters, and documentation at all district court levels.',
    icon: Scale,
    subAreas: [
      { name: 'Civil Suits', content: 'Civil suits at the district court level cover property disputes, money recovery, injunctions, partition, specific performance, and declaration suits. We draft plaints, written statements, applications, and appear for hearings — providing end-to-end civil litigation support from filing to execution of decree.' },
      { name: 'Criminal Trial Support', content: 'Criminal trials at the district court level involve FIR-based cases tried by Sessions Courts and Magistrates. We provide complete trial support including bail, chargesheet response, discharge applications, evidence strategy, examination and cross-examination preparation, and final arguments.' },
      { name: 'Bail Before Sessions Court', content: 'Regular bail applications and bail cancellation matters before the Sessions Court require careful preparation. We draft bail applications citing grounds of personal liberty, antecedents, cooperation with investigation, and parity with co-accused — supported by relevant High Court and Supreme Court precedents.' },
      { name: 'Family Disputes', content: 'District Family Courts handle matrimonial disputes including divorce, maintenance, custody, DV Act cases, and matrimonial home access. We represent clients before Family Courts across India with sensitivity, professionalism, and a focus on protecting our client\'s rights and welfare.' },
      { name: 'Recovery Matters', content: 'Money recovery suits, cheque bounce cases under Section 138 NI Act, and commercial recovery matters are handled through district courts. We draft plaints for recovery, summary suits, and Section 138 NI Act complaints — and provide representation through trial and execution.' },
      { name: 'Injunction Matters', content: 'Temporary injunctions, permanent injunctions, and mandatory injunctions protect property rights and prevent irreparable harm during litigation. We draft injunction applications under Order 39 CPC with supporting affidavits, balance of convenience analysis, and urgent listing requests.' },
      { name: 'Execution Proceedings', content: 'After obtaining a decree, execution proceedings are required to actually recover the decreed amount or enforce the decree. We assist in filing execution petitions, attachment proceedings, arrest applications, and all steps necessary to give effect to court decrees.' },
      { name: 'Evidence Support', content: 'Evidence preparation including witness list, documents, Affidavit of Evidence (AoE), cross-examination strategy, and objections under the Bharatiya Sakshya Adhiniyam (BSA) 2023 are critical to winning cases. We provide comprehensive evidence support and trial preparation.' },
    ],
    process: [
      { title: 'Case Filing', desc: 'Identifying the correct court, jurisdiction, and cause of action — then filing with complete documentation.' },
      { title: 'Trial Preparation', desc: 'Evidence gathering, witness preparation, and document organization for trial.' },
      { title: 'Hearing Representation', desc: 'Active representation through all hearing dates, arguments, and evidence recording.' },
      { title: 'Decree & Execution', desc: 'Following through to final decree and execution proceedings if needed.' },
    ],
    related: ['Civil Law', 'Criminal Law', 'Family Law', 'Property Law'],
    courts: ['Allahabad District Courts', 'Delhi District Courts', 'Bengaluru District Courts', 'Kolkata District Courts', 'District Courts Across India'],
  },
  {
    slug: 'criminal-law',
    title: 'Criminal Law',
    category: 'Criminal Practice',
    tagline: 'Defending your rights with experience, strategy and legal precision.',
    description: 'We assist clients in criminal litigation matters involving FIRs, bail, anticipatory bail, trial defence, criminal complaints, appeals, revisions, and legal strategy support under the Bharatiya Nagarik Suraksha Sanhita (BNSS) 2023 and Bharatiya Nyaya Sanhita (BNS) 2023.',
    icon: Shield,
    subAreas: [
      { name: 'FIR Registration & Guidance', content: 'A First Information Report (FIR) is the entry point into the criminal justice system. We guide victims in properly filing FIRs that capture all essential elements — offence details, time, place, and perpetrators. For accused, we provide immediate guidance on rights upon FIR registration, including the right to know the FIR contents, right to bail in bailable offences, and the right to legal counsel under Article 22.' },
      { name: 'Bail & Anticipatory Bail', content: 'Bail is the right to freedom — we fight for it vigorously. Under the BNSS 2023, bail applications for non-bailable offences are filed before the Magistrate, Sessions Court, or High Court. Anticipatory bail under Section 482 BNSS (438 CrPC equivalent) is filed before arrest. We draft comprehensive bail applications citing parity with co-accused, nature and gravity of offence, antecedents, cooperation with investigation, and flight risk assessment — backed by Supreme Court and High Court precedents on personal liberty under Article 21.' },
      { name: 'Criminal Trial Defence', content: 'A complete criminal defence strategy involves analysing the chargesheet, identifying weaknesses in the prosecution case, filing a discharge application before framing of charges, preparing witnesses, cross-examining prosecution witnesses effectively, and presenting a strong defence. We provide end-to-end trial support under the BNSS 2023 and BNS 2023 framework.' },
      { name: 'FIR Quashing', content: 'When an FIR is filed maliciously, lacks any offence, or is a civil dispute given criminal colour, it can be quashed by the High Court under Section 528 BNSS (482 CrPC equivalent). We research and draft quashing petitions identifying abuse of process, lack of ingredients of offence, and civil nature of dispute — with supporting Supreme Court judgments including State of Haryana v. Bhajanlal guidelines.' },
      { name: 'White Collar Crime', content: 'White collar crimes including cheating, fraud, criminal breach of trust, forgery, and financial fraud require understanding of both criminal law and commercial transactions. We assist accused in bail, trial defence, and parallel civil remedies, while assisting victims in complaint drafting, FIR registration, and coordination with Economic Offences Wing.' },
      { name: 'Cyber Crime Assistance', content: 'Cyber crimes under the IT Act 2000, BNS 2023, and DPDPA include online fraud, hacking, identity theft, cyberstalking, morphing, sextortion, and social media defamation. We assist victims in cybercell complaint filing, FIR registration, interim court orders for content removal, and civil remedies, while assisting accused in bail and trial defence in cyber crime courts.' },
      { name: 'Domestic Violence Criminal Issues', content: 'Domestic violence matters have both civil (DV Act) and criminal (498A BNS) dimensions. 498A BNS (formerly 498A IPC) relates to cruelty by husband and his relatives — a cognizable, non-bailable offence. We assist both complainants seeking protection and accused seeking bail, quashing, and trial defence in matrimonial criminal matters.' },
      { name: 'Appeals & Revisions', content: 'Criminal appeals from Magistrate orders go to Sessions Court; Sessions Court convictions can be appealed to High Court; and High Court judgments can be challenged in the Supreme Court via SLP. We provide complete criminal appellate litigation — bail pending appeal, drafting of appeals identifying legal and factual errors, and arguments before appellate courts.' },
      { name: 'POCSO Matters', content: 'Matters under the Protection of Children from Sexual Offences (POCSO) Act require extreme sensitivity, confidentiality, and professional ethics. Special POCSO Courts handle these cases with victim-friendly procedures and child-sensitive processes. We assist both in victim support and legal guidance, and in defence matters maintaining strict confidentiality and professional ethics.' },
    ],
    process: [
      { title: 'Emergency Consultation', desc: 'Immediate guidance on arrest, bail rights, and FIR matters — available urgently.' },
      { title: 'Bail Strategy', desc: 'Filing bail application at the earliest available opportunity with strong grounds.' },
      { title: 'Trial Preparation', desc: 'Discharge applications, evidence analysis, witness preparation, and cross-examination strategy.' },
      { title: 'Appellate Recourse', desc: 'Challenging unfavourable orders before Sessions Court, High Court, or Supreme Court.' },
    ],
    related: ['BNSS 2023', 'BNS 2023', 'BSA 2023', 'High Courts', 'Supreme Court'],
    courts: ['Sessions Courts', 'Magistrate Courts', 'Special Courts (POCSO, NI Act)', 'High Courts', 'Supreme Court'],
  },
  {
    slug: 'civil-law',
    title: 'Civil Litigation',
    category: 'Civil Practice',
    tagline: 'Protecting your civil rights and property interests with research-based precision.',
    description: 'We handle civil litigation matters relating to property disputes, recovery suits, injunctions, partition suits, declaration matters, possession disputes, contractual conflicts, and legal documentation. Civil litigation is based on legal rights, documents, evidence, ownership, agreements, and enforceable claims.',
    icon: FileText,
    subAreas: [
      { name: 'Property Disputes', content: 'Property disputes in India are among the most complex and emotionally charged legal matters. They involve title disputes, adverse possession claims, encroachment, disputed boundaries, and ownership conflicts between family members or strangers. We conduct thorough title searches, analyse revenue records and mutation entries, and draft comprehensive civil suits for declaration of title, mandatory injunction, or recovery of possession — backed by evidence including registered sale deeds, inheritance records, and judicial precedents on property law.' },
      { name: 'Recovery Suits', content: 'Money recovery suits can be filed under Order 37 CPC (summary suits) or as plenary suits when the defendant disputes the amount. We draft recovery plaints identifying the debt, default, and supporting documentation — promissory notes, agreements, invoices, and correspondence. For cheque bounce cases under Section 138 NI Act, we file criminal complaints in addition to civil recovery suits for maximum legal pressure.' },
      { name: 'Injunctions', content: 'Temporary injunctions under Order 39 Rule 1-2 CPC restrain a party from doing a particular act during the pendency of litigation. Permanent injunctions are final reliefs. We draft injunction applications with proper prima facie case analysis, balance of convenience, and irreparable harm — citing relevant precedents and urgency justification for ex-parte orders where needed.' },
      { name: 'Partition Suits', content: 'Partition suits among co-owners, family members, or HUF members for division of property require careful identification of shares, valuation, and court-appointed Receiver or Commissioner for measurement. We draft partition suits identifying all parties, shares, and relief including preliminary and final decree — managing the full lifecycle from filing to actual partition.' },
      { name: 'Declaration Suits', content: 'Suits for declaration under Section 34 Specific Relief Act seek a court declaration of the plaintiff\'s legal character, title, or right. They are filed when no consequential relief is needed immediately or when the plaintiff wishes to clarify a legal position. We draft declaration suits with careful identification of legal rights, cause of action, and entitlement to the declaratory decree.' },
      { name: 'Specific Performance', content: 'When a party refuses to perform a contract — especially for immovable property — the aggrieved party can file a suit for specific performance under the Specific Relief Act (as amended 2018). We draft specific performance suits with proof of readiness and willingness, valid agreement to sell, and demand for performance — along with urgent interim injunctions to prevent third-party sales.' },
      { name: 'Cheque Bounce Cases', content: 'Section 138 of the Negotiable Instruments Act makes dishonour of cheque a criminal offence. The creditor must send a statutory demand notice within 30 days of dishonour, and file complaint within 30 days of the notice period expiry. We draft demand notices, criminal complaints, and civil recovery suits in parallel — maximising recovery chances through dual legal routes.' },
      { name: 'Legal Notices', content: 'A legal notice is often the first formal step in resolving a dispute — it puts the opposite party on formal notice of your claim, establishes a timeline for pre-litigation compliance, and creates a legal record. We draft legal notices under various statutes — demand notices, eviction notices, notices for specific performance, and general legal notices — in clear, precise legal language.' },
    ],
    process: [
      { title: 'Document Verification', desc: 'Thorough review of all title documents, agreements, and evidence before proceeding.' },
      { title: 'Plaint Drafting', desc: 'Comprehensive plaint identifying cause of action, parties, and relief sought.' },
      { title: 'Interim Relief', desc: 'Urgent injunction or stay application to protect rights during litigation.' },
      { title: 'Trial & Arguments', desc: 'Evidence recording, cross-examination, and final arguments for decree.' },
    ],
    related: ['Property Law', 'Contract Law', 'Consumer Protection', 'Commercial Law'],
    courts: ['Civil Courts', 'Commercial Courts', 'High Courts', 'Consumer Forums'],
  },
  {
    slug: 'family-matrimonial',
    title: 'Family & Matrimonial Law',
    category: 'Family Practice',
    tagline: 'Sensitive, strategic guidance through life\'s most personal legal matters.',
    description: 'We provide assistance in sensitive matrimonial and family disputes with professionalism, confidentiality, and strategic legal support. Family disputes require a combination of empathy, legal knowledge, and strategic thinking to navigate effectively.',
    icon: HeartHandshake,
    subAreas: [
      { name: 'Mutual Divorce', content: 'Mutual divorce under Section 13-B Hindu Marriage Act (or equivalent provisions in Special Marriage Act) is available when both spouses agree to dissolve the marriage after living separately for one year. We facilitate the process — preparing the joint petition, first and second motion affidavits, and valuation of assets — and coordinate the entire court procedure including the mandatory six-month cooling period (which can be waived in appropriate cases after the Supreme Court judgment in Shilpa Sailesh).' },
      { name: 'Contested Divorce', content: 'Contested divorce is filed on grounds including cruelty (physical or mental), desertion, adultery, conversion, mental disorder, or irretrievable breakdown. We draft the divorce petition with detailed factual matrix, supporting evidence, and witness identification — and represent through the full contested trial including cross-examination and final arguments before Family Courts.' },
      { name: 'Maintenance & Alimony', content: 'Maintenance for wife, children, and parents can be claimed under multiple laws simultaneously — Section 125 CrPC (now BNSS 2023), Section 24/25 Hindu Marriage Act, Hindu Adoption and Maintenance Act, and Domestic Violence Act. We strategically choose the most favourable forum and draft applications establishing need, standard of living, and the respondent\'s income with documentary evidence.' },
      { name: '498A — Matrimonial Cruelty', content: '498A BNS (formerly 498A IPC) deals with cruelty by husband and his relatives toward a married woman. It is a cognizable, non-bailable, and non-compoundable offence. We assist both complainants in registering FIR, evidence collection, and trial — and accused in anticipatory bail, regular bail, quashing petitions, and trial defence in matrimonial cruelty cases.' },
      { name: 'Child Custody', content: 'Child custody disputes are decided based on the paramount consideration of the child\'s welfare. Courts consider age, gender, educational needs, bonding, and stability. We represent parents before Family Courts and High Courts — drafting custody applications, interim custody requests, and visitation right applications. For international custody disputes including Hague Convention matters, we provide specialized research and legal strategy.' },
      { name: 'Domestic Violence (DV Act)', content: 'The Protection of Women from Domestic Violence Act, 2005 provides protection orders, residence orders, custody orders, and monetary relief — all in one proceeding before the Magistrate. We assist victims in filing DV Act applications, obtaining emergency protection orders, and securing residence and maintenance — while assisting respondents who face false DV allegations in protection proceedings.' },
      { name: 'Family Settlements', content: 'Family property disputes and succession conflicts can often be resolved through negotiated family settlements — avoiding prolonged and expensive litigation. We draft comprehensive family settlement agreements that clearly identify all parties, shares, valuation methodology, timelines for execution, and consequences of breach — with proper stamp duty and registration compliance.' },
    ],
    process: [
      { title: 'Confidential Consultation', desc: 'Private, judgment-free discussion of your family situation and legal options.' },
      { title: 'Mediation Assessment', desc: 'Exploring whether mediation or negotiated settlement is possible before going to court.' },
      { title: 'Family Court Filing', desc: 'Drafting and filing in the appropriate Family Court or Magistrate Court.' },
      { title: 'Final Resolution', desc: 'Decree, settlement agreement, or court order finalising the matter with legal protection.' },
    ],
    related: ['Hindu Marriage Act', 'Special Marriage Act', 'DV Act', 'Guardianship Act'],
    courts: ['Family Courts', 'Magistrate Courts', 'Sessions Courts', 'High Courts'],
  },
  {
    slug: 'corporate-commercial',
    title: 'Corporate & Commercial Law',
    category: 'Corporate Practice',
    tagline: 'Comprehensive legal support for businesses, startups, and commercial entities.',
    description: 'We assist startups, businesses, firms, and commercial entities in legal documentation, compliance support, agreements, notices, contractual matters, and strategic legal advisory.',
    icon: Briefcase,
    subAreas: [
      { name: 'Business Agreements', content: 'Poorly drafted agreements are the leading cause of commercial disputes. We draft customised business agreements — service agreements, vendor contracts, distribution agreements, agency contracts, and general commercial contracts — identifying each party\'s obligations, payment terms, IP ownership, confidentiality, termination rights, dispute resolution mechanisms, and governing law. Every agreement is tailored to your specific business model and risk profile.' },
      { name: 'Startup Legal Support', content: 'Startups need lean but solid legal foundations. We assist startups with founders\' agreements identifying equity splits, vesting schedules, and roles; IP assignment agreements ensuring all founder-created IP belongs to the company; term sheet review and interpretation; employee stock option plan (ESOP) documentation; and regulatory compliance including DPIIT recognition documentation for tax exemptions.' },
      { name: 'NDA & Confidentiality Agreements', content: 'Non-Disclosure Agreements (NDAs) protect sensitive business information shared during negotiations, employment, or vendor relationships. We draft one-way and mutual NDAs that clearly define confidential information, permitted uses, duration, exclusions, and remedies for breach — with jurisdiction clauses appropriate to Indian law requirements and enforceability.' },
      { name: 'Partnership & LLP Documentation', content: 'Partnership deeds and LLP agreements define the relationship between partners — profit sharing, management rights, admission and exit procedures, dissolution mechanism, and dispute resolution. We draft comprehensive partnership deeds that protect all partners\' interests while facilitating smooth business operations and government registration requirements.' },
      { name: 'Employment Agreements', content: 'Employment agreements, HR policies, and appointment letters define the employer-employee relationship. We draft employment contracts with appropriate confidentiality, non-compete (note: Indian law limits enforceability), IP assignment, and termination clauses — reviewed for compliance with applicable labour codes, the Shops and Establishments Act, and industry-specific regulations.' },
      { name: 'Commercial Dispute Support', content: 'Commercial disputes between businesses — breach of contract, payment defaults, defective deliveries, intellectual property infringement, and unfair trade practices — can be resolved through civil litigation, arbitration, or negotiation. We assess the best forum, draft legal notices initiating the dispute formally, and provide complete litigation or arbitration support through resolution.' },
      { name: 'Compliance Advisory', content: 'Regulatory compliance for businesses in India spans multiple legislation — Companies Act, GST, labour codes, FEMA for foreign entities, consumer protection, and sector-specific regulations. We provide compliance audits identifying gaps, action plans for rectification, and drafting of compliance documents including internal policies, board resolutions, and regulatory filings.' },
    ],
    process: [
      { title: 'Business Assessment', desc: 'Understanding your business model, risks, and legal needs.' },
      { title: 'Documentation', desc: 'Professional drafting of all required commercial legal documents.' },
      { title: 'Compliance Review', desc: 'Identifying and addressing regulatory compliance gaps.' },
      { title: 'Ongoing Advisory', desc: 'Retainer-based legal advisory for continuing business needs.' },
    ],
    related: ['Contract Law', 'Company Law', 'IP Law', 'Employment Law'],
    courts: ['Commercial Courts', 'NCLT', 'Arbitration Tribunals', 'Civil Courts'],
  },
  {
    slug: 'constitutional-law',
    title: 'Constitutional Law',
    category: 'Constitutional Practice',
    tagline: 'Protecting fundamental rights through constitutional remedies.',
    description: 'We provide research and litigation assistance relating to constitutional rights, writ jurisdiction, public law disputes, administrative actions, and legal interpretation issues. Constitutional law requires specialized expertise in articles, precedents, and evolving judicial interpretation.',
    icon: BookOpen,
    subAreas: [
      { name: 'Right to Equality (Article 14)', content: 'Article 14 guarantees equality before law and equal protection of laws. It prohibits arbitrary State action through the twin tests of classification (intelligible differentia) and nexus. We draft writ petitions challenging arbitrary administrative orders, discriminatory legislation, and unreasonable classifications — citing the vast Article 14 jurisprudence from E.P. Royappa to the modern substantive equality framework.' },
      { name: 'Freedoms (Article 19)', content: 'Article 19 guarantees six freedoms including speech and expression, peaceful assembly, association, movement, residence, and profession. Restrictions must satisfy the tests of being by law, serving a specified State interest, and being reasonable. We challenge overbroad restrictions on freedoms — including internet shutdowns, gag orders, licence cancellations, and restrictions on associations — under Article 19.' },
      { name: 'Right to Life (Article 21)', content: 'Article 21 is the most expansive fundamental right — through decades of judicial interpretation, it now encompasses the right to health, education, livelihood, privacy (Justice K.S. Puttaswamy, 2017), dignified living, speedy trial, legal aid, and protection from torture. We draft Article 21 petitions in diverse contexts from healthcare denial to environmental pollution to prison conditions.' },
      { name: 'Writ Jurisdiction', content: 'The five writs — Habeas Corpus (release from illegal detention), Mandamus (compelling performance of duty), Certiorari (quashing illegal orders), Prohibition (restraining courts from exceeding jurisdiction), and Quo Warranto (challenging holding of public office) — are the tools of constitutional enforcement. We analyse the appropriate writ, draft the petition, and argue before High Courts and the Supreme Court.' },
      { name: 'Public Interest Litigation (PIL)', content: 'PIL was evolved by the Supreme Court to allow public-spirited citizens to vindicate constitutional rights of those unable to approach courts themselves. From environment to corruption to education to prison reform — PILs have transformed Indian public law. We identify genuine public interest issues, gather evidence, draft petitions, and manage PIL litigation before High Courts and the Supreme Court.' },
      { name: 'Administrative Law', content: 'Administrative law governs the exercise of government power — how it is exercised, the procedure followed, and the constraints on State action. Principles of natural justice (audi alteram partem, nemo judex in causa sua), procedural fairness, proportionality, and legitimate expectation protect citizens from arbitrary State action. We challenge administrative orders violating these principles before courts and tribunals.' },
      { name: 'Right to Information (RTI as Constitutional Right)', content: 'The Supreme Court has recognised the right to information as a fundamental right emanating from Articles 19(1)(a) and 21. Beyond the RTI Act mechanism, constitutional petitions can be filed when government bodies refuse to disclose information affecting fundamental rights, manipulate public discourse, or violate transparency obligations under constitutional law.' },
    ],
    process: [
      { title: 'Constitutional Analysis', desc: 'Identifying the exact constitutional provision and violation with supporting case law.' },
      { title: 'Writ Drafting', desc: 'Drafting the appropriate writ petition with grounds, precedents, and reliefs.' },
      { title: 'Arguments', desc: 'Strong constitutional arguments before the appropriate court.' },
      { title: 'Final Relief', desc: 'Securing declaration, mandamus, certiorari, or injunctive constitutional relief.' },
    ],
    related: ['Supreme Court', 'High Courts', 'Administrative Law', 'PIL'],
    courts: ['Supreme Court of India', 'All High Courts'],
  },
  {
    slug: 'arbitration-adr',
    title: 'Arbitration & ADR',
    category: 'Dispute Resolution',
    tagline: 'Efficient, confidential, and legally binding dispute resolution.',
    description: 'We assist in arbitration proceedings, mediation support, commercial dispute resolution, and structured legal negotiation mechanisms under the Arbitration and Conciliation Act, 1996 (as amended in 2015, 2019, and 2021).',
    icon: Scale,
    subAreas: [
      { name: 'Domestic Arbitration', content: 'Domestic arbitration under Part I of the Arbitration and Conciliation Act, 1996 provides a private, efficient, and binding dispute resolution mechanism for commercial disputes. We draft the statement of claim and statement of defence, assist in appointing arbitrators, attend arbitration hearings, and advise on evidence and procedural strategy through final award.' },
      { name: 'Arbitration Notice', content: 'Invoking arbitration begins with a proper arbitration notice under Section 21 of the Arbitration Act — identifying the dispute, invoking the arbitration clause, and proposing the arbitrator. We draft arbitration invocation notices that precisely identify the contractual basis for arbitration, the dispute, and compliance with notice requirements in the arbitration agreement.' },
      { name: 'Section 9 Interim Relief', content: 'Section 9 of the Arbitration Act allows courts to grant interim protection before or during arbitration — including injunctions to protect assets, appointment of a Receiver, or preservation of evidence. We draft urgent Section 9 applications with balance of convenience analysis and coordinate for urgent hearings before Commercial Courts or High Courts.' },
      { name: 'Appointment of Arbitrator', content: 'When parties fail to agree on an arbitrator, either party can approach the court under Section 11 for appointment. We draft Section 11 applications identifying the arbitration clause, notice history, and requesting the appropriate court to appoint an arbitrator — including sole arbitrators, three-member tribunals, and specialized institutional arbitration.' },
      { name: 'Award Challenges', content: 'An arbitral award can be challenged before courts on limited grounds under Section 34 — patent illegality, violation of public policy, conflict with Indian law, fraud, or corruption. We identify valid Section 34 grounds, draft challenge petitions with precise legal arguments, and coordinate for urgent stay of award enforcement during the challenge period.' },
      { name: 'Enforcement of Awards', content: 'Domestic arbitral awards are enforced as decrees of civil courts under Section 36. International arbitral awards under the New York Convention are enforced under Section 44. We assist in enforcement petitions, responding to Section 34 challenges, and execution proceedings when awards are not voluntarily complied with.' },
      { name: 'Mediation Support', content: 'Mediation under the Mediation Act, 2023 offers a structured, facilitated negotiation toward settlement. We advise clients on mediation strategy, prepare position papers, accompany clients to mediation sessions, assist in evaluating settlement proposals, and draft comprehensive mediated settlement agreements that are legally binding and enforceable as decrees.' },
    ],
    process: [
      { title: 'Dispute Analysis', desc: 'Evaluating the arbitration clause, applicable rules, and dispute suitability.' },
      { title: 'Arbitration Initiation', desc: 'Sending arbitration notice, appointing arbitrators, and filing claim.' },
      { title: 'Arbitration Proceedings', desc: 'Evidence, hearings, arguments, and full procedural compliance.' },
      { title: 'Award & Enforcement', desc: 'Securing and enforcing the final award — or challenging an adverse award.' },
    ],
    related: ['Contract Law', 'Commercial Law', 'Corporate Law', 'International Law'],
    courts: ['Arbitration Tribunals', 'Commercial Courts', 'High Courts', 'Supreme Court'],
  },
  {
    slug: 'international-law',
    title: 'International Law & Research',
    category: 'International Practice',
    tagline: 'Global legal research and comparative constitutional analysis.',
    description: 'NyayaSutra focuses on international legal developments, comparative constitutional systems, global governance structures, public international law, and cross-border legal research — bringing a global perspective to Indian legal practice.',
    icon: Globe,
    subAreas: [
      { name: 'Comparative Constitutional Law', content: 'Comparative constitutional law examines how different nations structure their fundamental law — constitutional design, rights protection, federalism, judicial review, and emergency powers. We research comparative constitutional systems — US, UK, Canadian, German, South African, and others — to enrich arguments before Indian courts on constitutional interpretation, especially in frontier areas like privacy, equality, and social rights.' },
      { name: 'International Human Rights', content: 'International human rights law — from the Universal Declaration of Human Rights to ICCPR, ICESCR, CEDAW, and CRC — creates obligations that India has voluntarily assumed through treaty ratification. We research international human rights standards for their persuasive value before Indian courts and advise on compliance and reporting obligations under international conventions.' },
      { name: 'International Arbitration Research', content: 'International commercial arbitration under UNCITRAL Rules, ICC Rules, SIAC Rules, or LCIA Rules involves complex questions of seat, governing law, enforcement under the New York Convention, and recognition of foreign awards in India. We provide research support for international arbitration matters including conflict of laws, choice of law analysis, and New York Convention enforcement strategy.' },
      { name: 'Foreign Investment Law', content: 'Foreign investment in India is regulated by FEMA, FDI Policy, and sector-specific regulations. We research regulatory frameworks for foreign investors entering India, FDI restrictions in regulated sectors, ODI guidelines for Indian entities investing abroad, and cross-border restructuring from a regulatory compliance perspective.' },
      { name: 'Extradition Matters', content: 'Extradition requests between India and foreign countries are governed by bilateral extradition treaties and the Extradition Act, 1962. We research extradition treaty provisions, grounds for refusal including political offence exception, dual criminality requirements, and procedural requirements — both for facilitating and resisting extradition.' },
      { name: 'Cross-border Legal Research', content: 'Cross-border legal research spans comparative law analysis, international conventions, UN resolutions, WTO dispute settlement, and multilateral treaty interpretation. We provide structured research reports on international law questions — from trade law to environmental agreements to cybersecurity conventions — for advocates, academics, and policy professionals.' },
    ],
    process: [
      { title: 'Research Question Definition', desc: 'Precisely identifying the international legal question and jurisdictions involved.' },
      { title: 'Multi-jurisdiction Research', desc: 'Comprehensive research across primary sources and academic commentary.' },
      { title: 'Analysis & Synthesis', desc: 'Clear analytical report with application to the Indian legal context.' },
      { title: 'Application', desc: 'Integrating international law insights into domestic legal arguments and strategy.' },
    ],
    related: ['Constitutional Law', 'Arbitration', 'Human Rights', 'Corporate Law'],
    courts: ['Supreme Court', 'High Courts', 'International Arbitration', 'UN Bodies'],
  },
  {
    slug: 'cyber-law',
    title: 'Cyber Law & Digital Matters',
    category: 'Digital Practice',
    tagline: 'Legal protection in the digital world — your rights online.',
    description: 'We assist in matters relating to cyber offences, online fraud, digital harassment, social media disputes, privacy concerns, and digital legal compliance under India\'s evolving cyber laws.',
    icon: Globe,
    subAreas: [
      { name: 'Cyber Fraud & Financial Crime', content: 'Online financial fraud — UPI fraud, phishing, identity theft, investment fraud, and social engineering — causes enormous financial loss. When you are a victim of cyber financial fraud, the first 24-48 hours are critical. We guide victims in immediate reporting to cybercell and NPCI (1930 helpline), FIR filing, banker notification, and court orders for freezing fraudulent accounts — maximising the chance of fund recovery.' },
      { name: 'Social Media Defamation', content: 'Defamatory content on social media — false statements of fact, morphed images, fake reviews, or impersonation accounts — can cause severe reputational damage. We draft defamation complaints, coordinate with cybercell for account identification, obtain court orders for content removal, and file civil suits for damages and permanent injunction against further publication.' },
      { name: 'Online Harassment & Cyberstalking', content: 'Online harassment and cyberstalking are criminal offences under the BNS 2023 (Sections 77, 78) and IT Act, 2000 (Sections 66A, 67). We guide victims in preserving evidence (screenshots with metadata), identifying perpetrators through legal process, FIR filing, and obtaining court protection orders — and provide legal defence for those wrongly accused of online harassment.' },
      { name: 'Hacking & Data Breach', content: 'Unauthorized access to computer systems, networks, or data under Section 66 IT Act is a serious criminal offence. For corporate victims of hacking and data breaches, we coordinate with cybersecurity experts, draft incident response notices, guide regulatory disclosure obligations under CERT-In guidelines and DPDPA, and pursue civil and criminal remedies against perpetrators.' },
      { name: 'Digital Evidence', content: 'Digital evidence — electronic documents, emails, WhatsApp messages, social media posts, CCTV footage, call detail records — is governed by the Bharatiya Sakshya Adhiniyam (BSA) 2023. We advise on proper evidence preservation including metadata, hash verification, and Section 65B certification requirements — critical for admissibility before courts.' },
      { name: 'Data Protection Compliance', content: 'The Digital Personal Data Protection Act (DPDPA) 2023 creates obligations for Data Fiduciaries processing personal data of Indian citizens. We advise on consent management framework, privacy policy drafting, Data Protection Officer (DPO) appointment, breach notification procedures, and compliance with DPDPA and upcoming implementing rules.' },
      { name: 'IT Act Section 69 & Interception Orders', content: 'Government surveillance and data interception orders under Sections 69, 69A, and 69B of the IT Act raise serious privacy concerns. We research the legal basis, procedural safeguards, and constitutional validity of interception orders — assisting individuals and civil society organizations in challenging disproportionate surveillance affecting fundamental rights under Articles 19 and 21.' },
    ],
    process: [
      { title: 'Immediate Response', desc: 'Guiding victims in immediate cyber crime response — report preservation and complaint.' },
      { title: 'Cybercell Coordination', desc: 'FIR filing and coordination with cybercell and CERT-In.' },
      { title: 'Legal Action', desc: 'Civil and criminal proceedings including court orders for interim relief.' },
      { title: 'Recovery & Redressal', desc: 'Pursuing compensation, content removal, and account freezing orders.' },
    ],
    related: ['IT Act 2000', 'BNS 2023', 'DPDPA 2023', 'BSA 2023'],
    courts: ['Cyber Crime Cells', 'Magistrate Courts', 'High Courts', 'Data Protection Board'],
  },
  {
    slug: 'rti-human-rights',
    title: 'RTI & Human Rights',
    category: 'Public Law',
    tagline: 'Empowering citizens through transparency and rights protection.',
    description: 'We provide assistance relating to Right to Information (RTI) applications, Human Rights Commission matters, public grievances, administrative injustice, and legal awareness.',
    icon: Flag,
    subAreas: [
      { name: 'RTI Application Drafting', content: 'A well-drafted RTI application targets the correct Public Information Officer (PIO), precisely identifies the information sought, and is framed to avoid unnecessary exemption claims under Section 8 of the RTI Act. We draft strategic RTI applications identifying the correct public authority, framing questions precisely, and targeting the most relevant PIO — including for Central Ministries (online portal), State Governments, High Courts, and public sector undertakings.' },
      { name: 'RTI First Appeal', content: 'When the PIO refuses information, provides incomplete response, or does not reply within 30 days, a First Appeal lies to the First Appellate Authority (FAA) of the same public authority. We draft First Appeals that systematically rebut the exemptions claimed, cite RTI Act provisions and Central Information Commission (CIC) or State Information Commission orders supporting disclosure, and request orders for information within a specified time.' },
      { name: 'RTI Second Appeal to CIC/SIC', content: 'If the First Appellate Authority is unsatisfactory, a Second Appeal lies before the Central Information Commission (for Central Government RTIs) or State Information Commission (for State Government RTIs). We draft Second Appeals citing CIC and SIC precedents, information commission orders on similar issues, and requesting penalty orders against non-compliant PIOs under Section 20 RTI Act.' },
      { name: 'NHRC Complaints', content: 'The National Human Rights Commission (NHRC) investigates human rights violations by State authorities — police brutality, custodial deaths, denial of healthcare, forced labour, trafficking, and rights of marginalized groups. We draft NHRC complaints with documentary evidence, witness identification, and specific prayer for investigation and compensation — and track the complaint through the NHRC process.' },
      { name: 'RTI for Legal Proceedings', content: 'RTI is a powerful tool in litigation — used to obtain government documents, public records, inspection reports, and correspondence that may be critical evidence in pending legal matters. We strategically file RTI applications timed to litigation milestones, target specific documents needed for court cases, and use the information obtained to strengthen legal arguments and establish facts.' },
      { name: 'Administrative Complaints', content: 'Administrative complaints before the Chief Secretary, departmental heads, and vigilance authorities can address corruption, maladministration, and denial of public services. We draft structured administrative complaints identifying the violation, legal basis for the grievance, and specific relief sought — with parallel RTI applications to create documentary evidence of the grievance.' },
    ],
    process: [
      { title: 'Information Identification', desc: 'Identifying exactly what information is needed and from which public authority.' },
      { title: 'RTI Application', desc: 'Precisely drafted RTI application targeting the correct PIO.' },
      { title: 'Appeals', desc: 'First appeal to FAA, then second appeal to Information Commission if needed.' },
      { title: 'Commission Hearing', desc: 'Representation before CIC/SIC with supporting arguments for disclosure.' },
    ],
    related: ['Constitutional Law', 'Administrative Law', 'Public Law', 'PIL'],
    courts: ['Information Commissions', 'High Courts', 'NHRC / SHRC', 'Supreme Court'],
  },
  {
    slug: 'consumer-tribunal',
    title: 'Consumer & Tribunal Matters',
    category: 'Consumer Practice',
    tagline: 'Standing up for consumers against unfair trade practices and deficient services.',
    description: 'We assist in consumer disputes, tribunal proceedings, service-related disputes, and quasi-judicial matters before all three tiers of consumer commissions and various tribunals under the Consumer Protection Act, 2019.',
    icon: Users,
    subAreas: [
      { name: 'Consumer Complaints', content: 'The Consumer Protection Act, 2019 provides consumers with a powerful redressal mechanism. District Consumer Commissions handle complaints up to ₹50 lakhs, State Consumer Commissions up to ₹2 crore, and the National Consumer Commission (NCDRC) for amounts above ₹2 crore. We draft comprehensive consumer complaints identifying deficiency of service or unfair trade practice with supporting documentary evidence and consumer precedents from NCDRC.' },
      { name: 'E-Commerce & Online Disputes', content: 'E-commerce platforms — Amazon, Flipkart, Meesho, Swiggy, Zomato — are squarely covered by the Consumer Protection Act, 2019 and the E-Commerce Rules. Online fraud, non-delivery, counterfeit goods, misleading advertisements, and unfair return policies are actionable before consumer commissions. We draft consumer complaints and use ONDC/e-Daakhil platforms for faster digital filing.' },
      { name: 'Medical Negligence', content: 'Medical negligence cases require expert evidence on the standard of care and the deviation from it causing harm to the patient. The Supreme Court in Jacob Mathew v. State of Punjab established the Bolam test for medical negligence in India. We assist families in obtaining medical expert opinions, filing consumer complaints and/or civil suits, and navigating the complex intersection of civil liability, criminal negligence, and consumer protection in medical cases.' },
      { name: 'Insurance Claim Disputes', content: 'Insurance companies frequently repudiate valid claims on technical grounds — incomplete documentation, misrepresentation allegations, delayed intimation, or policy exclusion interpretation. We draft consumer complaints and civil suits challenging wrongful claim repudiation, citing IRDAI regulations, insurance contract interpretation principles, and consumer commission precedents ordering claim payment with compensation.' },
      { name: 'Banking & Finance Disputes', content: 'Banks are "service providers" under the Consumer Protection Act — making banking service deficiencies actionable before consumer commissions. Wrongful EMI charges, incorrect credit reporting to CIBIL, hidden fee deductions, credit card disputes, loan processing failures, and online banking fraud are all consumer matters. We draft banking consumer complaints with supporting transaction evidence and RBI circulars on customer protection.' },
      { name: 'RERA Complaints', content: 'The Real Estate (Regulation and Development) Act, 2016 protects homebuyers from builder delays, false promises, and quality defects. RERA Authorities in each state adjudicate builder-buyer disputes and award interest at 10.75% for delayed possession along with refund or possession. We draft RERA complaints with agreement analysis, correspondence evidence, and calculation of interest and compensation due.' },
    ],
    process: [
      { title: 'Consumer Consultation', desc: 'Evaluating the complaint — identifying deficiency, limitation period, and correct forum.' },
      { title: 'Legal Notice', desc: 'Sending legal notice to give the opposite party a final opportunity before complaint filing.' },
      { title: 'Commission Filing', desc: 'Filing at the appropriate consumer commission — District, State, or National.' },
      { title: 'Arguments & Award', desc: 'Representation through hearings until final compensation order.' },
    ],
    related: ['Consumer Protection Act 2019', 'RERA', 'Insurance Law', 'Banking Law'],
    courts: ['District Consumer Commissions', 'State Consumer Commissions', 'NCDRC', 'RERA Authorities'],
  },
  {
    slug: 'legal-research',
    title: 'Legal Research & Drafting',
    category: 'Research & Documentation',
    tagline: 'Precision-drafted legal documents and deep, research-based legal analysis.',
    description: 'Professional legal drafting and research form the foundation of effective litigation. NyayaSutra focuses on structured drafting, memorial preparation, legal analysis, and litigation documentation for advocates, law firms, students, and businesses.',
    icon: Search,
    subAreas: [
      { name: 'Legal Notices', content: 'A well-drafted legal notice is the formal commencement of a legal dispute. It puts the opponent on notice, establishes the timeline for pre-litigation compliance, and creates an important legal record. We draft legal notices under all applicable statutes — demand notices under the NI Act, eviction notices, notices for specific performance, employment-related notices, and general legal demand notices — in precise, unambiguous legal language with proper cause of action identification.' },
      { name: 'Petition & Plaint Drafting', content: 'Court petitions and plaints are the most critical documents in any litigation — they define the scope of the case, identify the parties and cause of action, and set out the reliefs sought. We draft writ petitions, civil plaints, criminal complaints, consumer complaints, arbitration claims, and tribunal petitions — with careful identification of jurisdiction, limitation, and all essential legal elements.' },
      { name: 'SLP & Writ Drafting', content: 'Supreme Court Special Leave Petitions and High Court writ petitions require a specialized drafting approach — identifying the constitutional or legal question, framing concise grounds, and presenting them in the format and style expected by constitutional courts. We draft SLPs and writs with the precision and depth required for effective presentation before apex courts.' },
      { name: 'Written Statements & Replies', content: 'A well-drafted written statement in civil suits or reply to writ petitions can turn the tide of litigation. We draft written statements that raise every available legal defence — limitation, estoppel, part performance, waiver, and substantive defences — organized in a clear, court-friendly format that anticipates the plaintiff\'s arguments and preempts them effectively.' },
      { name: 'Bail Applications', content: 'Bail applications before Magistrates, Sessions Courts, and High Courts require tailored drafting for each forum. We research bail-relevant facts — co-accused bail precedents, antecedents, investigation stage, nature of offence, maximum punishment — and draft bail applications that present the strongest possible case for release, supported by relevant Supreme Court and High Court precedents on personal liberty.' },
      { name: 'Moot Court Memorials', content: 'Moot court memorial drafting is both a competitive skill and foundational legal training. We draft comprehensive moot court memorials — for Petitioner and Respondent sides — with complete argument structure, proposition of law, case law citations, and counter-arguments. We also provide oral argument coaching, issue-identification workshops, and post-moot feedback for law students and institutional moot court teams.' },
      { name: 'Case Research & Briefing', content: 'Legal research is the backbone of effective litigation. We provide case research services covering Supreme Court and High Court precedents on specific legal propositions, statutory interpretation research, legislative history analysis, and comparative law research. Our research notes are concise, citation-accurate, and directly usable in arguments — sourced from Manupatra, SCC Online, and official court databases.' },
      { name: 'Affidavits & Declarations', content: 'Affidavits are sworn statements of facts that carry evidential weight before courts, tribunals, and administrative authorities. We draft affidavits of evidence, affidavits in support of applications, income affidavits, residence affidavits, and general declarations — ensuring they comply with CPC requirements on stamp duty, notarization, and proper verification format as per the applicable court rules.' },
    ],
    process: [
      { title: 'Requirement Understanding', desc: 'Precisely understanding the legal document needed and its purpose.' },
      { title: 'Research Foundation', desc: 'Building the research base of law, precedents, and facts before drafting.' },
      { title: 'Professional Drafting', desc: 'Precise, accurate drafting in appropriate legal language and format.' },
      { title: 'Review & Delivery', desc: 'Review, amendment, and timely delivery in required format.' },
    ],
    related: ['All Practice Areas', 'Supreme Court', 'High Courts', 'Moot Courts'],
    courts: ['All Courts', 'Tribunals', 'Academic Institutions', 'Administrative Bodies'],
  },
  {
    slug: 'pocso-sensitive',
    title: 'POCSO & Sensitive Matters',
    category: 'Sensitive Practice',
    tagline: 'Professional, confidential, and ethical legal guidance in sensitive criminal matters.',
    description: 'We provide legal assistance in sensitive matters relating to POCSO cases, sexual offence allegations, victim support, defence assistance, bail matters, and trial-related legal guidance — with strict adherence to confidentiality and professional ethics.',
    icon: AlertCircle,
    subAreas: [
      { name: 'POCSO Legal Assistance', content: 'The Protection of Children from Sexual Offences (POCSO) Act, 2012 provides for child-friendly court procedures, in-camera proceedings, prohibition on disclosure of child victim\'s identity, special courts, and enhanced punishments. We provide sensitive, confidential legal guidance — for both victim support and defence — with strict professional ethics and compliance with all POCSO procedural protections.' },
      { name: 'Bail in POCSO Matters', content: 'Bail in POCSO cases is difficult due to the stringent legislative framework — courts must be satisfied that the accused is not likely to commit further offences and is not a danger to witnesses. We draft bail applications with complete character evidence, surety details, undertakings, and arguments on personal liberty — with careful analysis of Section 29 POCSO reverse burden provisions and Supreme Court bail jurisprudence.' },
      { name: 'Trial Support & Defence', content: 'POCSO trials involve special provisions — in-camera hearing, videography of child testimony, use of intermediary for examination, and single examination of child victim. Effective trial defence requires careful analysis of the FIR, medical evidence, school records, and digital evidence — identifying inconsistencies while maintaining judicial sensitivity required for these cases.' },
    ],
    process: [
      { title: 'Confidential Consultation', desc: 'Strictly private initial consultation with absolute confidentiality.' },
      { title: 'Legal Position Assessment', desc: 'Careful, ethical assessment of the complete legal position.' },
      { title: 'Court Strategy', desc: 'Appropriate legal strategy with full compliance with POCSO Act.' },
      { title: 'Representation', desc: 'Sensitive, professional representation maintaining judicial decorum.' },
    ],
    related: ['Criminal Law', 'Child Protection', 'POCSO Act', 'BNS 2023'],
    courts: ['Special POCSO Courts', 'Sessions Courts', 'High Courts'],
  },
];
